apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      automountServiceAccountToken: false
      containers:
        - name: keycloak
          image: bitnami/keycloak:26
          env:
            - name: KEYCLOAK_DATABASE_HOST
              value: keycloak-db-service
            - name: KEYCLOAK_DATABASE_NAME
              value: keycloak
            - name: KEYCLOAK_DATABASE_USER
              value: keycloak
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: db-password
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: admin-password
            - name: KC_PROXY
              value: 'edge'
            - name: KC_PROXY_ADDRESS_FORWARDING
              value: 'true'
            - name: KC_HEALTH_ENABLED
              value: 'true'
            - name: KC_METRICS_ENABLED
              value: 'true'
            - name: KC_HTTP_ENABLED
              value: 'true'
          ports:
            - name: http
              containerPort: 8080
            # - name: https
            #   containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: ClusterIP
  ClusterIP: None
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8484
      targetPort: 8080
    # - name: https
    #   port: 8443
    #   targetPort: 8443
