apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      automountServiceAccountToken: false
      containers:
        - image: bitnami/keycloak:26
          imagePullPolicy: Always
          name: keycloak
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: keycloak-admin
                  name: keycloak-secret
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keycloak-admin-password
                  name: keycloak-secret
            - name: KC_PROXY
              value: edge
            - name: KEYCLOAK_DATABASE_NAME
              value: 'keycloak'
            - name: KEYCLOAK_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: db-username
                  name: keycloak-secret
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: keycloak-secret
            - name: KEYCLOAK_DATABASE_HOST
              value: 'keycloak-db-service'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
