apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: keycloak-db
          image: bitnami/postgresql:14
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: M1thr4nd1r
              # valueFrom:
              #   secretKeyRef:
              #     name: keycloak-db-secret
              #     key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db-service
spec:
  selector:
    app: keycloak-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
