apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: keycloak-db-pvc
      containers:
        - name: keycloak-db
          image: bitnami/postgresql:14
          volumeMounts:
            - name: db-data
              mountPath: /bitnami/postgresql
          env:
            - name: POSTGRESQL_DATABASE
              value: keycloak
            - name: POSTGRESQL_USERNAME
              value: keycloak
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db-service
spec:
  selector:
    app: keycloak-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
