apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    ingress-controller: nginx
  name: keycloak-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  #   nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: keycloak.monarka.local
      http:
        paths:
          - backend:
              service:
                name: keycloak
                port:
                  number: 80
            # path: /
            # pathType: ImplementationSpecific
  tls:
    - hosts:
        - fake
      secretName: keycloak-pki
