apiVersion: v1
data:
  db_password: TTF0aHI0bmQxcg==
  db_username: a2V5Y2xvYWsK
  keycloak_admin: YWRtaW4=
  keycloak_admin_password: YWRtaW4=
kind: Secret
metadata:
  name: keycloak-secret
  namespace: default
type: Opaque
