apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monarka-store
  namespace: argocd
spec:
  project: default

  source:
    chart: monarka-project
    repoURL: https://github.com/Monarka-store/monarka-project
    targetRevision: HEAD
    helm:
      releaseName: k8s/monarka-store
      valuesFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
