apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: default
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: api
          imagePullPolicy: Always
          image: monarkastoreapirn.azurecr.io/monarka-api:latest
          env:
            - name: PORT
              value: '8585'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: db_url
                  name: api-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt_secret
                  name: api-secret
            - name: KEYCLOAK_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: keycloak_jwt_secret
                  name: api-secret
            - name: KEYCLOAK_CLIENT_ID_API
              valueFrom:
                secretKeyRef:
                  key: keycloak_client_id_api
                  name: api-secret
            - name: KEYCLOAK_CLIENT_SECRET_API
              valueFrom:
                secretKeyRef:
                  key: keycloak_client_secret_api
                  name: api-secret
            - name: KEYCLOAK_ISSUER_API
              # value: 'http://keycloak.default.svc.cluster.local/realms/monarka'
              value: 'https://keycloak.monarka.local/realms/monarka'
            - name: KEYCLOAK_GRANT_TYPE
              valueFrom:
                secretKeyRef:
                  key: keycloak_grant_type
                  name: api-secret
          ports:
            - containerPort: 8585
              protocol: TCP
