apiVersion: v1
data:
  db_url: cG9zdGdyZXNxbDovL2FwaWRiX293bmVyOjBPUGpDVXRrdTlkR0BlcC1zbWFsbC1xdWVlbi1hNTQ5c2cxNy51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9hcGlkYj9zc2xtb2RlPXJlcXVpcmUK
  jwt_secret: TTF0aHI0bmQxcgo=
  keycloak_jwt_secret: LS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2ejNtb2Y5QXVtUXcyRFFUbk5BYzg2SHhYOW1BUmdJMGNxZHVNOHJsSmdrZ2k5ZmU3RlRnK1h5VHZMNXBwenNlSDMwZXFsUkJXUkxxc005RGw2WkVwclBvOXJsZlhRZUoyQVJqTWRwT3J5VWh0a01zRlh3dUJWRHBiTHhlanhFL1hLQ1VSS0E2b2RHVmNaZ00vWjBkZEJWbFBTdTVpZzQ0QVljRHhsMy9WSXRJMG1NMmJJdUVtQWRMd3JZVkEyVmlNOFJrUDlNdm9uc3dESFNaQWo2VzMyaCtrbFVaSHJqUXhuZldwa2FHRUlxMjRYQlRDNGp1VFFIVTJ1RnhDSSs4QnlLRHZxeGJaOGN5VlVxM2dHNzBkWmJ1dGdxVkZ4Qzk5dmx4dy9Cazc0QU1HWmJBdStCU1k4aTJSK3pmTFFycEJpM2tmcjVhdXh3YTlWZllZNCs5QlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  keycloak_client_id_api: bmVzdGpzCg==
  keycloak_client_secret_api: RlJtT253cE9XTE52azh2NnI2TlA3SEdyREhLeG5qbjkK
  keycloak_issuer_api: aHR0cDovL2tleWNsb2FrLm1vbmFya2EubG9jYWwvcmVhbG1zL21vbmFya2EK
  keycloak_grant_type: cGFzc3dvcmQK
kind: Secret
metadata:
  name: api-secret
type: Opaque
