apiVersion: v1
data:
  db_url: cG9zdGdyZXNxbDovL2FwaWRiX293bmVyOjBPUGpDVXRrdTlkR0BlcC1zbWFsbC1xdWVlbi1hNTQ5c2cxNy51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9hcGlkYj9zc2xtb2RlPXJlcXVpcmUK
  jwt_secret: TTF0aHI0bmQxcgo=
  keycloak_jwt_secret: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzKzdwRngzbEVpUFB2QTgxUGxSempBcHlFSWNtVGgwaGNlM0RzWHB0UFNwQ0JZUk8rc0Q3QnZQOEVBZy94YzI1a3JWZTUzcEk1a2RMV2RWZ1hyZjNHN012MDJJWFhHbVRlWFAyYmc5VVhaOFZMVVZXWjZacncxUDY3OGcrZFFwVW5NY2IzVzhKZnVpb3ZtOE0xbEkyai9RY1h1R0FYWkRMTi9HRUFBeG50cXFQbnF6Z01lN1pMZlhIV25JM1JmV3FYWDhxRXFhbm1vYW1uWUJ0YXpDZGVRQ2lScmJUdUZiSERSOUhpejIwZWE4ZjIxYlE5Wk1UT0RVKytOUjZDaVNqUkhVTHpvOE5lQUpWZXpBbldhdEdtQUNpK0w5elczSHgzaVY2ZFJtQzV5aitHb1dDRURUcXpuaU9DNEhJRjE0MkxzNlVER2VTNC9NaFZUMGNYZDFHeFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  keycloak_client_id_api: bmVzdGpzCg==
  keycloak_client_secret_api: Sm4xNmJzU3BlM0tSRmREWlBwTkFwUUVKbDNGWm9idWwK
  keycloak_issuer_api: aHR0cDovL2tleWNsb2FrLm1vbmFya2EubG9jYWwvcmVhbG1zL21vbmFya2EK
  keycloak_grant_type: cGFzc3dvcmQK
kind: Secret
metadata:
  name: api-secret
type: Opaque
