apiVersion: v1
data:
  db_url: cG9zdGdyZXNxbDovL2FwaWRiX293bmVyOjBPUGpDVXRrdTlkR0BlcC1zbWFsbC1xdWVlbi1hNTQ5c2cxNy51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9hcGlkYj9zc2xtb2RlPXJlcXVpcmU=
  jwt_secret: TTF0aHI0bmQxcg==
  keycloak_jwt_secret: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5ZWpYNVVIWExnRzRJTTZCclJHQmtBZERXRnFKMnZ1U2RyWW5YY1dYMkxsRmowQ1RXQkN2ZXNqcFB6bk04R05EMzBoUXZQWGZpdURXL1NsMFN2TDVCMVlEaVdtSVFOK092TEMwYmcyak1qQkFyQVZmWS9wbkRDeTZMQitWbUwzZVVHWFlRSVhhaW8xWWRDZGtHaUNWeFZjZkRoNjUwdHhrZFJDV20zVVoxMDNtalJ0Zm1NMTJNMzJLRE9qL09LNmM3aStkVlFPNkZnb3lzdmtqOERpdEhocm1rMk83cmZ2dzh5WmJGNC9aL0o0SGhteEM0NFcxL2xwYnNyNksvalQ4cFkybWRXaHkxR2dQbjFvaE1mYXhHeGpITTBmeWhSY2txMVJpODlwRkxUNmtUYW5ITEw5czNoazU1NHFZaTFjNjQxWTVHNlRGWmlZQjVySUFHazZ2U1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
  keycloak_client_id_api: bmVzdGpz
  keycloak_client_secret_api: MXltOExhcWZRUFA0VmNwTlI5cjA2SjhnMmRJS3R5VEo=
  keycloak_issuer_api: aHR0cHM6Ly9rZXljbG9hay5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsL3JlYWxtcy9tb25hcmth
  keycloak_grant_type: cmVmcmVzaF90b2tlbg==
kind: Secret
metadata:
  name: api-secret
type: Opaque
