apiVersion: v1
data:
  db_url: cG9zdGdyZXNxbDovL2FwaWRiX293bmVyOjBPUGpDVXRrdTlkR0BlcC1zbWFsbC1xdWVlbi1hNTQ5c2cxNy51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9hcGlkYj9zc2xtb2RlPXJlcXVpcmUK
  jwt_secret: TTF0aHI0bmQxcgo=
  keycloak_jwt_secret: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3TlFwS0tobzBENSt2K0VvMGdHank5MHllcWdRaWJyNDZ6UUZ1TUxPT2JQT2QxZTFnZSs1c1A3TDFyRTBuNmFMc1pwbUVLczRocTFlemNKNzIyZG12djNueUpaY0NvQ3VUbWtRclNUREZ1WFI5VkhLMmNvRjloL3RwMnpqMnlBdXp4TFl6dDBTVTJqUWtKbXMreFVseEd6bkwzeWJwOU1zc2tKRERMa3NhcjR0S05YUHZMVGxMcnZURlZQRkZuc0RvMTg0MEZLNTdyOFkxL1FlZE1HWXVFK2lLWWViL2tFTmhUR1UxZ1A3bkh5ZFhEZXNpc3hXeVk5YWV1ZU5nc0tDUWx5U01wTDBhNmk0WGI0c0RXSmdEY2hrSmdyN091RWcyc0dlSUUwRVBiMWh0TDNyc2VKeVYwMUZEM0NQMzA1MU5FZHJlOCt4Y0lpc09SY29neXk3bVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  keycloak_client_id_api: bmVzdGpzCg==
  keycloak_client_secret_api: c29CYXlEYkRGck5iMWlsUjV0TndmWXNGYW1IQ0NERzcK
  keycloak_issuer_api: aHR0cDovL2tleWNsb2FrLm1vbmFya2EubG9jYWwvcmVhbG1zL21vbmFya2EK
  keycloak_grant_type: cGFzc3dvcmQK
kind: Secret
metadata:
  name: api-secret
type: Opaque
