apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: api
          image: monarkastoreapirn.azurecr.io/monarka-api:latest
          env:
            - name: PORT
              value: '8585'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: jwt-secret
            - name: KEYCLOAK_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: keycloak-jwt-secret
            - name: KEYCLOAK_CLIENT_ID_API
              value: nestjs
            - name: KEYCLOAK_CLIENT_SECRET_API
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: keycloak-client-secret-api
            - name: KEYCLOAK_ISSUER_API
              value: 'http://keycloak-service:8484/realms/monarka'
            - name: KEYCLOAK_GRANT_TYPE
              value: 'password'
          ports:
            - containerPort: 8585
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 8585
      targetPort: 8585
