apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client-monarka-store
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Monarka-store/monarka-project.git
    targetRevision: main
    path: k8s/client
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
