apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/tu-usuario/tu-repo'
    targetRevision: main
    path: k8s/nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
