apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      automountServiceAccountToken: false
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
              storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "1"
              storage: "2Gi"
          env:
            {{- range .Values.keycloak.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}