apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgresql
          image: '{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}'
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
              storage: '512Mi'
            limits:
              memory: '512Mi'
              cpu: '500m'
              storage: '1Gi'
          env:
            - name: POSTGRESQL_DATABASE
              value: '{{ .Values.postgresql.auth.database }}'
            - name: POSTGRESQL_USERNAME
              value: '{{ .Values.postgresql.auth.username }}'
            - name: POSTGRESQL_PASSWORD
              value: '{{ .Values.postgresql.auth.password }}'
