apiVersion: v1
data:
  keycloak_client_id: bmV4dGpz
  keycloak_client_secret: ODJ1TnFuWENCbmtvYnZlcWw0ZEN1N0tGUnYxMWE1OFU=
  keycloak_issuer: aHR0cHM6Ly9rZXljbG9hay5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsL3JlYWxtcy9tb25hcmth
  nextauth_url: aHR0cHM6Ly93d3cubW9uYXJrYS5sb2NhbA==
  nextauth_secret: zSjrEisERvaK4y2T1Hav6F/DMsMFS9omifUOJJVbqt0=
  next_public_api_url: aHR0cHM6Ly9hcGkuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbC9hcGkvdjE=
kind: Secret
metadata:
  name: client-secret
type: Opaque
