apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monarka-store
  namespace: argocd
spec:
  project: default

  source:
    repoURL: ''
    targetRevision: HEAD
    path: helm/keycloak
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
